// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PayamBack.Data;

#nullable disable

namespace PayamBack.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260721161201_AddLevelMarkaz")]
    partial class AddLevelMarkaz
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PayamBack.Models.Audit.Sabeghe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Dastgah")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IdRecordTagirDahande")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpSystem")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Moroorgar")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RoozHafte")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Table")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TozihTagirat")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ZamanLogOut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ZamanLogin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ZamanTagir")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sabeghes");
                });

            modelBuilder.Entity("PayamBack.Models.Core.Daneshjoo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChapDast")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CodeReshteMahalGhabooliSanjesh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Jens")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MahalSodoor")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("MarkazAzmoonId")
                        .HasColumnType("int");

                    b.Property<int?>("MarkazId")
                        .HasColumnType("int");

                    b.Property<int?>("MarkazTermiId")
                        .HasColumnType("int");

                    b.Property<string>("Mobile")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Naam")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NaamKhanevadegi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Naampedar")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ReshtehId")
                        .HasColumnType("int");

                    b.Property<string>("ShenasayeFaragirAtbaaKhareji")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShomareDaneshjooee")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShomareDavtalabi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShomareGozarnameYaKartHoviyat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShomareMelli")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ShomareParvande")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShomareSanjesh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShomareShenasname")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly?>("TarikhTavalod")
                        .HasColumnType("date");

                    b.Property<string>("TermVorood")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VazeeyatParvande")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("MarkazAzmoonId");

                    b.HasIndex("MarkazId");

                    b.HasIndex("MarkazTermiId");

                    b.HasIndex("ReshtehId");

                    b.ToTable("Daneshjoos");
                });

            modelBuilder.Entity("PayamBack.Models.Core.Karmand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeMelli")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Emza")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("MarkazAsliId")
                        .HasColumnType("int");

                    b.Property<int?>("MarkazId")
                        .HasColumnType("int");

                    b.Property<string>("Mobile")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Mobile2")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Naam")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NaameKhanevadeghi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TelefonDakheli")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TelefonGhayreMostaghim")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TelefonMostaghim")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("MarkazAsliId");

                    b.HasIndex("MarkazId");

                    b.ToTable("Karmands");
                });

            modelBuilder.Entity("PayamBack.Models.Core.Markaz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CodeMarkaz")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodeOstan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodePosti")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool?>("Dakheli")
                        .HasColumnType("bit");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.Property<string>("MahalMarkaz")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NaamMarkaz")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NaamOstan")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nahiyeh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VahedMarkaz")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("Vazeeyat")
                        .HasColumnType("bit");

                    b.Property<string>("WebSite")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CodeMarkaz")
                        .IsUnique()
                        .HasDatabaseName("IX_Markaz_CodeMarkaz")
                        .HasFilter("[CodeMarkaz] IS NOT NULL");

                    b.ToTable("Markazes");
                });

            modelBuilder.Entity("PayamBack.Models.Core.MoshakhasatAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CodeMelli")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CodePosti")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Mobile")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Mobile2")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Naam")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NaameKhanevadeghi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TelefonDakheli")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TelefonGhayreMostaghim")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TelefonMostaghim")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("MoshakhasatAdmins");
                });

            modelBuilder.Entity("PayamBack.Models.Core.Ostad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeOstadi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Emza")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Jens")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MahalEshteghal")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MarkazAsliId")
                        .HasColumnType("int");

                    b.Property<int?>("MarkazId")
                        .HasColumnType("int");

                    b.Property<string>("MartabeElmi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mobile")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Mobile2")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Naam")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NaamKhanevadegi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NaamPedar")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NoeBimeh")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("NoeHamkari")
                        .HasColumnType("int");

                    b.Property<string>("SazmanMarboote")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShomareMelli")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ShomareShenasname")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ShomarehBimeh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TarikhTavalod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool?>("Vazeeat")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CodeOstadi")
                        .IsUnique()
                        .HasDatabaseName("IX_Ostad_CodeOstadi")
                        .HasFilter("[CodeOstadi] IS NOT NULL");

                    b.HasIndex("MarkazAsliId");

                    b.HasIndex("MarkazId")
                        .HasDatabaseName("IX_Ostad_MarkazId");

                    b.ToTable("Ostads");
                });

            modelBuilder.Entity("PayamBack.Models.Core.OstadMadrak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Grayesh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("GrooheAmoozeshiId")
                        .HasColumnType("int");

                    b.Property<int?>("Maghta")
                        .HasColumnType("int");

                    b.Property<string>("MahalAkhz")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("OstadId")
                        .HasColumnType("int");

                    b.Property<bool?>("PishFarz")
                        .HasColumnType("bit");

                    b.Property<string>("Reshteh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TasvirMadrak")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("GrooheAmoozeshiId");

                    b.HasIndex("OstadId", "PishFarz")
                        .HasDatabaseName("IX_OstadMadrak_OstadId_PishFarz");

                    b.ToTable("OstadMadraks");
                });

            modelBuilder.Entity("PayamBack.Models.Edu.GrooheAmoozeshi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeDaneshkade")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodeGrooheAmoozeshi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NaamDaneshkadeh")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OnvanGrooheAmoozeshi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("GrooheAmoozeshis");
                });

            modelBuilder.Entity("PayamBack.Models.Edu.Reshteh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeMaghta")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodeReshte")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodeReshteDoRaghami")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int?>("GrooheAmoozeshiId")
                        .HasColumnType("int");

                    b.Property<string>("Maghta")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OnvanReshte")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TermEamal")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TermVorood")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("GrooheAmoozeshiId");

                    b.ToTable("Reshtehs");
                });

            modelBuilder.Entity("PayamBack.Models.Edu.SaatBargozariKelasha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeSaat")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<bool?>("Hozoori")
                        .HasColumnType("bit");

                    b.Property<bool?>("Majazi")
                        .HasColumnType("bit");

                    b.Property<string>("OnvanSaat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SaatPayan")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("SaatShoroo")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Id");

                    b.ToTable("SaatBargozariKelashas");
                });

            modelBuilder.Entity("PayamBack.Models.Edu.TaghvimTermi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CodeHafteh")
                        .HasColumnType("int");

                    b.Property<int?>("CodeRooz")
                        .HasColumnType("int");

                    b.Property<string>("CodeSaateTatili")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CodeTerm")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Hafteh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OnvanMonasebat")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RoozHafteh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly?>("Tarikh")
                        .HasColumnType("date");

                    b.Property<string>("Tozihat")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("Vazeeyat")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TaghvimTermis");
                });

            modelBuilder.Entity("PayamBack.Models.Edu.Term", b =>
                {
                    b.Property<string>("CodeTerm")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OnvanTerm")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("TarikheDastrasi")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("TarikheEraeeDars")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("TarikhePayanClass")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("TarikhePayanDars")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("TarikhePayanMojavezMarakez")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("TarikheShorooClass")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("TarikheShorooMojavezMarakez")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("TermJari")
                        .HasColumnType("date");

                    b.Property<bool?>("Vazeeyat")
                        .HasColumnType("bit");

                    b.HasKey("CodeTerm");

                    b.ToTable("Terms");
                });

            modelBuilder.Entity("PayamBack.Models.Identity.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CodeRole")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Emza")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool?>("Vazeeyat")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("PayamBack.Models.Identity.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("AdminId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DaneshjooId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("KarmandId")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("OstadId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool?>("Vazeeyat")
                        .HasColumnType("bit");

                    b.Property<bool?>("VazeeyatMovaghat")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("DaneshjooId");

                    b.HasIndex("KarmandId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("OstadId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PayamBack.Models.Identity.AppUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("MarkazId")
                        .HasColumnType("int");

                    b.Property<bool?>("RolePishFarz")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("MarkazId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId", "MarkazId")
                        .IsUnique()
                        .HasDatabaseName("IX_AppUserRole_UserId_RoleId_MarkazId")
                        .HasFilter("[MarkazId] IS NOT NULL");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("PayamBack.Models.Identity.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PermissionName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Vazeeat")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("PayamBack.Models.Identity.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Resource")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Permission_Name")
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("PayamBack.Models.Identity.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<bool?>("Vazeeat")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique()
                        .HasDatabaseName("IX_RolePermission_RoleId_PermissionId")
                        .HasFilter("[RoleId] IS NOT NULL AND [PermissionId] IS NOT NULL");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("PayamBack.Models.Schedule.BarnamehHaftegiOstad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("A")
                        .HasColumnType("int");

                    b.Property<int?>("B")
                        .HasColumnType("int");

                    b.Property<int?>("C")
                        .HasColumnType("int");

                    b.Property<string>("CodeTerm")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("D")
                        .HasColumnType("int");

                    b.Property<int?>("E")
                        .HasColumnType("int");

                    b.Property<int?>("F")
                        .HasColumnType("int");

                    b.Property<int?>("G")
                        .HasColumnType("int");

                    b.Property<int?>("H")
                        .HasColumnType("int");

                    b.Property<bool?>("Jozeiat")
                        .HasColumnType("bit");

                    b.Property<int?>("MarkazId")
                        .HasColumnType("int");

                    b.Property<int?>("OstadId")
                        .HasColumnType("int");

                    b.Property<string>("RoozeHafteh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CodeTerm");

                    b.HasIndex("MarkazId");

                    b.HasIndex("OstadId", "CodeTerm", "MarkazId", "RoozeHafteh")
                        .IsUnique()
                        .HasDatabaseName("IX_BarnamehHaftegiOstad_CodeOstad_CodeTerm_MarkazId_RoozeHafteh")
                        .HasFilter("[OstadId] IS NOT NULL AND [CodeTerm] IS NOT NULL AND [MarkazId] IS NOT NULL AND [RoozeHafteh] IS NOT NULL");

                    b.ToTable("BarnamehHaftegiOstads");
                });

            modelBuilder.Entity("PayamBack.Models.Schedule.BarnamehTermiOstad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("A")
                        .HasColumnType("int");

                    b.Property<int?>("B")
                        .HasColumnType("int");

                    b.Property<int?>("C")
                        .HasColumnType("int");

                    b.Property<string>("CodeTerm")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("D")
                        .HasColumnType("int");

                    b.Property<int?>("E")
                        .HasColumnType("int");

                    b.Property<int?>("F")
                        .HasColumnType("int");

                    b.Property<int?>("G")
                        .HasColumnType("int");

                    b.Property<int?>("H")
                        .HasColumnType("int");

                    b.Property<int?>("MarkazId")
                        .HasColumnType("int");

                    b.Property<int?>("OstadId")
                        .HasColumnType("int");

                    b.Property<string>("RoozeHafteh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("TA")
                        .HasColumnType("bit");

                    b.Property<bool?>("TB")
                        .HasColumnType("bit");

                    b.Property<bool?>("TC")
                        .HasColumnType("bit");

                    b.Property<bool?>("TD")
                        .HasColumnType("bit");

                    b.Property<bool?>("TE")
                        .HasColumnType("bit");

                    b.Property<bool?>("TF")
                        .HasColumnType("bit");

                    b.Property<bool?>("TG")
                        .HasColumnType("bit");

                    b.Property<bool?>("TH")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("Tarikh")
                        .HasColumnType("date");

                    b.Property<bool?>("Vazeeat")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CodeTerm");

                    b.HasIndex("MarkazId");

                    b.HasIndex("OstadId", "CodeTerm", "MarkazId", "Tarikh")
                        .IsUnique()
                        .HasDatabaseName("IX_BarnamehTermiOstad_CodeOstad_CodeTerm_MarkazId_Tarikh")
                        .HasFilter("[OstadId] IS NOT NULL AND [CodeTerm] IS NOT NULL AND [MarkazId] IS NOT NULL AND [Tarikh] IS NOT NULL");

                    b.ToTable("BarnamehTermiOstads");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("PayamBack.Models.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("PayamBack.Models.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("PayamBack.Models.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("PayamBack.Models.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PayamBack.Models.Audit.Sabeghe", b =>
                {
                    b.HasOne("PayamBack.Models.Identity.AppUser", "User")
                        .WithMany("Sabeghes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");
                });

            modelBuilder.Entity("PayamBack.Models.Core.Daneshjoo", b =>
                {
                    b.HasOne("PayamBack.Models.Core.Markaz", "MarkazAzmoon")
                        .WithMany()
                        .HasForeignKey("MarkazAzmoonId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PayamBack.Models.Core.Markaz", "Markaz")
                        .WithMany("Daneshjoos")
                        .HasForeignKey("MarkazId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PayamBack.Models.Core.Markaz", "MarkazTermi")
                        .WithMany()
                        .HasForeignKey("MarkazTermiId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PayamBack.Models.Edu.Reshteh", "Reshteh")
                        .WithMany("Daneshjoos")
                        .HasForeignKey("ReshtehId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Markaz");

                    b.Navigation("MarkazAzmoon");

                    b.Navigation("MarkazTermi");

                    b.Navigation("Reshteh");
                });

            modelBuilder.Entity("PayamBack.Models.Core.Karmand", b =>
                {
                    b.HasOne("PayamBack.Models.Core.Markaz", "MarkazAsli")
                        .WithMany()
                        .HasForeignKey("MarkazAsliId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PayamBack.Models.Core.Markaz", "Markaz")
                        .WithMany("Karmands")
                        .HasForeignKey("MarkazId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Markaz");

                    b.Navigation("MarkazAsli");
                });

            modelBuilder.Entity("PayamBack.Models.Core.Ostad", b =>
                {
                    b.HasOne("PayamBack.Models.Core.Markaz", "MarkazAsli")
                        .WithMany()
                        .HasForeignKey("MarkazAsliId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PayamBack.Models.Core.Markaz", "Markaz")
                        .WithMany("Ostads")
                        .HasForeignKey("MarkazId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Markaz");

                    b.Navigation("MarkazAsli");
                });

            modelBuilder.Entity("PayamBack.Models.Core.OstadMadrak", b =>
                {
                    b.HasOne("PayamBack.Models.Edu.GrooheAmoozeshi", "GrooheAmoozeshi")
                        .WithMany()
                        .HasForeignKey("GrooheAmoozeshiId");

                    b.HasOne("PayamBack.Models.Core.Ostad", "Ostad")
                        .WithMany("OstadMadraks")
                        .HasForeignKey("OstadId");

                    b.Navigation("GrooheAmoozeshi");

                    b.Navigation("Ostad");
                });

            modelBuilder.Entity("PayamBack.Models.Edu.Reshteh", b =>
                {
                    b.HasOne("PayamBack.Models.Edu.GrooheAmoozeshi", "GrooheAmoozeshi")
                        .WithMany("Reshtehs")
                        .HasForeignKey("GrooheAmoozeshiId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("GrooheAmoozeshi");
                });

            modelBuilder.Entity("PayamBack.Models.Identity.AppUser", b =>
                {
                    b.HasOne("PayamBack.Models.Core.MoshakhasatAdmin", "MoshakhasatAdmin")
                        .WithMany()
                        .HasForeignKey("AdminId");

                    b.HasOne("PayamBack.Models.Core.Daneshjoo", "Daneshjoo")
                        .WithMany()
                        .HasForeignKey("DaneshjooId");

                    b.HasOne("PayamBack.Models.Core.Karmand", "Karmand")
                        .WithMany()
                        .HasForeignKey("KarmandId");

                    b.HasOne("PayamBack.Models.Core.Ostad", "Ostad")
                        .WithMany()
                        .HasForeignKey("OstadId");

                    b.Navigation("Daneshjoo");

                    b.Navigation("Karmand");

                    b.Navigation("MoshakhasatAdmin");

                    b.Navigation("Ostad");
                });

            modelBuilder.Entity("PayamBack.Models.Identity.AppUserRole", b =>
                {
                    b.HasOne("PayamBack.Models.Core.Markaz", "Markaz")
                        .WithMany("AppUserRoles")
                        .HasForeignKey("MarkazId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PayamBack.Models.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PayamBack.Models.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Markaz");
                });

            modelBuilder.Entity("PayamBack.Models.Identity.Menu", b =>
                {
                    b.HasOne("PayamBack.Models.Identity.Menu", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("PayamBack.Models.Identity.RolePermission", b =>
                {
                    b.HasOne("PayamBack.Models.Identity.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PayamBack.Models.Identity.AppRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PayamBack.Models.Schedule.BarnamehHaftegiOstad", b =>
                {
                    b.HasOne("PayamBack.Models.Edu.Term", "Term")
                        .WithMany()
                        .HasForeignKey("CodeTerm");

                    b.HasOne("PayamBack.Models.Core.Markaz", "Markaz")
                        .WithMany("BarnamehHaftegiOstads")
                        .HasForeignKey("MarkazId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PayamBack.Models.Core.Ostad", "Ostad")
                        .WithMany("BarnamehHaftegiOstads")
                        .HasForeignKey("OstadId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Markaz");

                    b.Navigation("Ostad");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("PayamBack.Models.Schedule.BarnamehTermiOstad", b =>
                {
                    b.HasOne("PayamBack.Models.Edu.Term", "Term")
                        .WithMany()
                        .HasForeignKey("CodeTerm");

                    b.HasOne("PayamBack.Models.Core.Markaz", "Markaz")
                        .WithMany("BarnamehTermiOstads")
                        .HasForeignKey("MarkazId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PayamBack.Models.Core.Ostad", "Ostad")
                        .WithMany("BarnamehTermiOstads")
                        .HasForeignKey("OstadId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Markaz");

                    b.Navigation("Ostad");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("PayamBack.Models.Core.Markaz", b =>
                {
                    b.Navigation("AppUserRoles");

                    b.Navigation("BarnamehHaftegiOstads");

                    b.Navigation("BarnamehTermiOstads");

                    b.Navigation("Daneshjoos");

                    b.Navigation("Karmands");

                    b.Navigation("Ostads");
                });

            modelBuilder.Entity("PayamBack.Models.Core.Ostad", b =>
                {
                    b.Navigation("BarnamehHaftegiOstads");

                    b.Navigation("BarnamehTermiOstads");

                    b.Navigation("OstadMadraks");
                });

            modelBuilder.Entity("PayamBack.Models.Edu.GrooheAmoozeshi", b =>
                {
                    b.Navigation("Reshtehs");
                });

            modelBuilder.Entity("PayamBack.Models.Edu.Reshteh", b =>
                {
                    b.Navigation("Daneshjoos");
                });

            modelBuilder.Entity("PayamBack.Models.Identity.AppUser", b =>
                {
                    b.Navigation("Sabeghes");
                });

            modelBuilder.Entity("PayamBack.Models.Identity.Menu", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("PayamBack.Models.Identity.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
